### PR TITLE
DAM-2102 Cleans up mods

### PR DESCRIPTION
**Pull request by svjoshua**
I tweaked a bunch of the mods here in preparation for updates.

### CODE REVIEW

**Comment by svjoshua** [comment]
I am writing a comment on this PR.... I know it can't be merged and I don't care.

**Comment by svjoshua** [comment]
Crap, the fieldname was problematic. Does this work?

**Comment by svjoshua** [comment]
Okay, this one should actually populate in the ticket.

**Comment by svjoshua** [comment]
Neat, I have that working. We can now capture all of the discussion here. 

I think this is important because:

- We don't have duplication
- We only need to access Jira to start new work or review WIP
- Another thing

Okay did that list come through?

**Comment by svjoshua** [comment]
Okay, I tweaked the formatting of the comment. Lets go ham on the formatting here.

# This is a heading.
**This is bold!**
_This is italic!_

> This is a quote!

`This is code! const foo = "banana";`
[I have linked to Google!](https://www.google.com)

- Item 1
- Item 2
- Item 3

1. Numbered List 1
2. Numbered List 2
3. Numbered List 3

This is a task.... no idea what they look like.

Calling out my other GitHub Account @evenmoor 

Making a reference. #9

**Comment by svjoshua** [comment]
Okay, I had to fix the url so we can link directly to the comments on GitHub instead of their JSON data.

**Review by evenmoor — CHANGES_REQUESTED** [review]
I think we need to do some more work here. There appears to be a spelling issue on line 5

**Review by evenmoor — CHANGES_REQUESTED** [review]
This is a rework to see if the flow is working correctly.

**Review by evenmoor — CHANGES_REQUESTED** [review]
This is a test to see if we can successfully kick an item back in the Jira workflow.

**Review by evenmoor — CHANGES_REQUESTED** [review]
bacon is cool but can we do better?

**Pull request closed without merging**
